---
  include-modules:
    - About
    - Data
    - Prediction:
        module-type: "file"
        location: "/Users/jreps/Documents/shinyCombined/inst/shiny/modules/prediction"
        version: "5.0.4"
        env-inputs:
          databaseConnectionEnv: "predictionConnection"
        inputs:
          targetDialect: "redshift" 
          myTableAppend: ""
    - Prediction-diagnostic:
        module-type: "file"
        location: "/Users/jreps/Documents/shinyCombined/inst/shiny/modules/prediction-diagnostic"
        version: "5.0.4"
        env-inputs:
          databaseConnectionEnv: "predictionDiagnosticConnection"
        inputs:
          targetDialect: "redshift" 
          myTableAppend: ""